### PR TITLE
Add ability to upsert multiple contacts

### PR DESCRIPTION
**Pull request by rdsida**
In the ExpressPigeon Docs upsert with a list is possible to avoid multiple api calls.  Currently this gem will not accept a list because it will nest the array of contacts one extra level which results in a `{"status"=>"error", "code"=>400, "message"=>"malformed request"}` .

### CODE REVIEW

**Comment by ipolevoy** [comment]
@rdsida is this a bug or enhancement?

**Comment by rdsida** [comment]
@ipolevoy seems like an enhancement.  While the express pigeon endpoint supports being given multiple contacts, this gem does not currently support being given multiple contacts to update through upsert.  I should probably update the documentation above the `upsert` method as well.

**Comment by ipolevoy** [comment]
@rdsida your changes are fine, thank you

**Comment by ipolevoy** [comment]
@rdsida , you can use expresspigeon-ruby (0.1.2) with your changes

**Pull request merged**
